spring:
    application:
        name: UserAuthenticationService_Sept2024
    datasource:
        url: jdbc:mysql://localhost:3306/userdb
        username: root
        password: Surya@123
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQLDialect

